### ISSUE TITLE
3D Scan fails

### ISSUE THREAD

**Issue by HUDiwan** [scanse/sweep-3d-scanner#54]
Hello,

I am trying to run the 3D Scanner but it fails. I have attached/included the error it prints in the log file. Any suggestions how I can fix it?

Error Output:
[scanner_output.log](https://github.com/scanse/sweep-3d-scanner/files/2432008/scanner_output.log)

Scanner app listening at http://:::8080
Use a browser on another device to navigate to http://172.24.1.1:8080
Someone made a request!
Traceback (most recent call last):
  File "/home/pi/code/scanse/sweep-3d-scanner/scanner/scanner.py", line 330, in <module>

    main(argsdict)
  File "/home/pi/code/scanse/sweep-3d-scanner/scanner/scanner.py", line 268, in main
    base = scanner_base.ScannerBase(use_dummy=use_dummy)
  File "/home/pi/code/scanse/sweep-3d-scanner/scanner/scanner_base.py", line 38, in __init__
    self.motor_hat = self.Adafruit_MotorHAT()
  File "build/bdist.linux-armv7l/egg/Adafruit_MotorHAT/Adafruit_MotorHAT_Motors.py", line 261, in __init__
  File "build/bdist.linux-armv7l/egg/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 59, in __init__
  File "build/bdist.linux-armv7l/egg/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 95, in setAllPWM
  File "build/bdist.linux-armv7l/egg/Adafruit_GPIO/I2C.py", line 114, in write8
  File "build/bdist.linux-armv7l/egg/Adafruit_PureIO/smbus.py", line 236, in write_byte_data
IOError: [Errno 121] Remote I/O error

Child process quit with code : 1
Doublechecking child process is dead...
Scan process is still alive... attempting kill + cleanup again.
Attempting to forcefully kill child process...
Spawning cleanup process...
Doublechecking child process is dead...
Scan process is still alive... attempting kill + cleanup again.
Attempting to forcefully kill child process...
Spawning cleanup process...
Traceback (most recent call last):
  File "/home/pi/code/scanse/sweep-3d-scanner/scanner/cleanup.py", line 70, in <module>

    main(argsdict)
  File "/home/pi/code/scanse/sweep-3d-scanner/scanner/cleanup.py", line 40, in main
    release_motors(use_dummy=arg_dict['use_dummy'])
  File "/home/pi/code/scanse/sweep-3d-scanner/scanner/cleanup.py", line 26, in release_motors
    motor_hat = Adafruit_MotorHAT()
  File "build/bdist.linux-armv7l/egg/Adafruit_MotorHAT/Adafruit_MotorHAT_Motors.py", line 261, in __init__
  File "build/bdist.linux-armv7l/egg/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 59, in __init__
  File "build/bdist.linux-armv7l/egg/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 95, in setAllPWM
  File "build/bdist.linux-armv7l/egg/Adafruit_GPIO/I2C.py", line 114, in write8
  File "build/bdist.linux-armv7l/egg/Adafruit_PureIO/smbus.py", line 236, in write_byte_data
IOError: [Errno 121] Remote I/O error

Traceback (most recent call last):
  File "/home/pi/code/scanse/sweep-3d-scanner/scanner/cleanup.py", line 70, in <module>

    main(argsdict)
  File "/home/pi/code/scanse/sweep-3d-scanner/scanner/cleanup.py", line 40, in main
    release_motors(use_dummy=arg_dict['use_dummy'])
  File "/home/pi/code/scanse/sweep-3d-scanner/scanner/cleanup.py", line 26, in release_motors
    motor_hat = Adafruit_MotorHAT()
  File "build/bdist.linux-armv7l/egg/Adafruit_MotorHAT/Adafruit_MotorHAT_Motors.py", line 261, in __init__
  File "build/bdist.linux-armv7l/egg/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 59, in __init__

Regards,
HUDiwan

**Comment by bramburn** [comment]
can you check you have the correct hardware?
